name: breast_sono_vision
description: "The Flutter mobile application for the BreastSonoVision project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  get: ^4.7.2
  shared_preferences: ^2.5.3
  file_picker: ^10.1.2
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  path: ^1.9.0
  google_fonts: ^6.2.1
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  lottie: ^3.2.0
  gal: ^2.3.1
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/animation/
    - assets/image/
    - .env
